### ISSUE TITLE
🛑 OTW-WEB(v50) is down

### ISSUE THREAD

**Issue by daamable-sknk** [sknkwoxs/upptime#210]
In [`2b564a1`](https://github.com/sknkwoxs/upptime/commit/2b564a17c890a1187b6387ad7b64a255c59f22cd
), OTW-WEB(v50) (https://v50.oxfamtrailwalker.or.kr) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by mozodev** [comment]
ssl 만료 (2024년 9월 2일 월요일 오전 8:59:59)
