### ISSUE TITLE
🛑 APCEIU CDI is down

### ISSUE THREAD

**Issue by daamable-sknk** [sknkwoxs/upptime#37]
In [`4ecaf10`](https://github.com/sknkwoxs/upptime/commit/4ecaf10fa6a8f5806bc71fde43d13ccfc7e4e671
), APCEIU CDI (https://gcedcurriculum.org) was **down**:
- HTTP code: 503
- Response time: 835 ms

**Comment by mozodev** [comment]
cafe24 cloud console 에서 재부팅했음
